"""
Kernelsoul - RuleCompiler v1.0
AI-based natural language → DSL rule compiler.
Manual Section: v2.0 planning
"""
import json, os, re, sys
from typing import Dict, List, Optional


class RuleCompiler:
    """Compiles natural language character descriptions into DSL rules via AI."""

    def __init__(self, ai_bridge, config_dir: str):
        self.bridge = ai_bridge
        self.config_dir = config_dir
        self._load_template()

    def _load_template(self):
        """Load the rule compiler prompt template."""
        prompt_path = os.path.join(self.config_dir, "rule_compiler_prompt.txt")
        if os.path.exists(prompt_path):
            with open(prompt_path, "r", encoding="utf-8") as f:
                self.template = f.read()
        else:
            self.template = """Generate character rules in JSON from this description:\n{character_description}"""
        # Load DSL validator
        sys.path.insert(0, os.path.dirname(self.config_dir))
        from dsl_compiler import DSLCompiler
        self.dsl_compiler = DSLCompiler()

    def compile(self, character_description: str) -> dict:
        """Compile natural language description into structured rules.

        Returns: {
            "character_rules": [...],
            "conditional_memories": [...],
            "suggested_variables": {...},
            "raw_response": str
        }
        """
        filled_prompt = self.template.replace("{character_description}", character_description)
        system = "You are a character rule compiler. Output ONLY valid JSON, no explanations."
        try:
            response = self.bridge.generate(system, filled_prompt)
            result = self._parse_response(response)
            result["raw_response"] = response
            return result
        except Exception as e:
            return {"error": str(e), "character_rules": [], "conditional_memories": [], "suggested_variables": {}}

    def _parse_response(self, response: str) -> dict:
        """Parse AI response into structured rules JSON."""
        # Extract JSON from response
        json_str = response
        # Try code block
        m = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", response)
        if m:
            json_str = m.group(1)
        # Try raw JSON
        try:
            data = json.loads(json_str)
        except json.JSONDecodeError:
            # Try to find JSON object boundaries
            m = re.search(r"\{[\s\S]*\}", json_str)
            if m:
                try:
                    data = json.loads(m.group(0))
                except json.JSONDecodeError:
                    return {"error": "Failed to parse AI response as JSON", "character_rules": [], "conditional_memories": [], "suggested_variables": {}}
            else:
                return {"error": "No JSON found in response", "character_rules": [], "conditional_memories": [], "suggested_variables": {}}

        # Validate structure
        rules = data.get("character_rules", [])
        memories = data.get("conditional_memories", [])
        variables = data.get("suggested_variables", {})

        # Validate each rule has required fields
        validated_rules = []
        for r in rules:
            if not isinstance(r, dict):
                continue
            validated = {
                "id": r.get("id", f"rule_{len(validated_rules)+1}"),
                "trigger": r.get("trigger", ""),
                "trigger_keywords": r.get("trigger_keywords", []),
                "condition": r.get("condition", {}),
                "actions": r.get("actions", []),
                "description": r.get("description", ""),
            }
            validated_rules.append(validated)

        validated_memories = []
        for m in memories:
            if not isinstance(m, dict):
                continue
            validated_memories.append({
                "id": m.get("id", f"mem_{len(validated_memories)+1}"),
                "content": m.get("content", ""),
                "unlock_condition": m.get("unlock_condition", {}),
                "unlocked": m.get("unlocked", False),
            })

        return {
            "character_rules": validated_rules,
            "conditional_memories": validated_memories,
            "suggested_variables": variables if isinstance(variables, dict) else {},
        }

    def to_dsl(self, rules: List[dict]) -> str:
        """Convert compiled rules list to DSL source text."""
        lines = []
        lines.append("# Auto-generated by RuleCompiler")
        lines.append("")

        for r in rules:
            # WHEN clause
            trigger = r.get("trigger", "")
            keywords = r.get("trigger_keywords", [])
            if keywords:
                kw_str = ", ".join(keywords)
                lines.append(f"WHEN {trigger} KEYWORDS {kw_str}")
            else:
                lines.append(f"WHEN {trigger}")

            # IF condition
            cond = r.get("condition", {})
            if cond:
                ct = cond.get("type", "compare")
                field = cond.get("field", "")
                value = cond.get("value", "")
                if ct == "compare" and field:
                    lines.append(f"  IF {field} <= {value}")

            # THEN actions
            lines.append("  THEN")
            actions = r.get("actions", [])
            if isinstance(actions, list):
                for a in actions:
                    if not isinstance(a, dict):
                        continue
                    at = a.get("type", "")
                    if at == "apply_state" or at == "SET":
                        for k, v in a.items():
                            if k not in ("type", "description"):
                                lines.append(f"    SET {k} = {v}")
                    elif at == "delta" or at == "CHANGE":
                        field2 = a.get("field", a.get("variable", ""))
                        delta = a.get("delta", a.get("value", 0))
                        if field2:
                            lines.append(f"    CHANGE {field2} BY {delta}")
                    elif at == "force_tone" or at == "FORCE":
                        tone = a.get("tone", a.get("value", ""))
                        if tone:
                            lines.append(f"    FORCE tone = {tone}")
                    elif at == "unlock_memory" or at == "UNLOCK":
                        mem_id = a.get("memory_id", a.get("id", ""))
                        if mem_id:
                            lines.append(f"    UNLOCK {mem_id}")
                    elif at == "add_item" or at == "ADD_ITEM":
                        item = a.get("item", "")
                        if item:
                            lines.append(f"    ADD_ITEM {item}")
                    elif at == "remove_item" or at == "REMOVE_ITEM":
                        item = a.get("item", "")
                        if item:
                            lines.append(f"    REMOVE_ITEM {item}")
                    elif at == "set_bg" or at == "SET_BG":
                        bg = a.get("bg", a.get("value", ""))
                        if bg:
                            lines.append(f"    SET_BG {bg}")

            lines.append("")  # blank line between rules

        return "\n".join(lines)

    def save_rules(self, rules_data: dict, char_dir: str):
        """Save compiled rules to a character directory.
        Writes character_rules.json + generates character.dsl.
        """
        # Write character_rules.json
        rules_path = os.path.join(char_dir, "character_rules.json")
        output = {
            "rules": rules_data.get("character_rules", []),
            "conditional_memories": rules_data.get("conditional_memories", []),
            "suggested_variables": rules_data.get("suggested_variables", {}),
            "compiled_by": "RuleCompiler v1.0",
        }
        with open(rules_path, "w", encoding="utf-8") as f:
            json.dump(output, f, ensure_ascii=False, indent=2)

        # Generate DSL
        dsl_text = self.to_dsl(rules_data.get("character_rules", []))
        dsl_path = os.path.join(char_dir, "character.dsl")
        with open(dsl_path, "w", encoding="utf-8") as f:
            f.write(dsl_text)

        return rules_path, dsl_path
